# -*- mode: ruby -*-
# vi: set ft=ruby :


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
SERVER_IP = "192.168.0.5"
NUMBER_OF_WORKERS= 1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.provision "shell", inline: $script
  config.vm.provision :reload

    config.vm.define "server" do |server|
      server.vm.network "private_network", ip: "#{SERVER_IP}"
      server.vm.hostname = "server"
      server.vm.synced_folder "~/consul_haproxy" , "/vagrant/consul_template"

      server.vm.provision "shell", inline: "printf 'export HOST_IP_E=#{SERVER_IP}\n'  >> ~/.profile"
      server.vm.provision "shell", inline: "printf 'export DNS_IP_E=$(ip a | grep 'docker0' | grep inet | cut -d \" \" -f 6 | cut -d \"/\" -f 1)'  >> ~/.profile"
      
      server.vm.provision :docker
      server.vm.provision :docker_compose, yml: "/vagrant/consul_template/consul_server/docker-compose.yml", rebuild: true, run: "always"
    end
  (1..NUMBER_OF_WORKERS).each do |instance_number|
    
    config.vm.define "worker-#{instance_number}" do |worker|
      worker.vm.network "private_network", type: "dhcp"
      worker.vm.hostname = "worker-#{instance_number}"
      worker.vm.synced_folder "~/consul_haproxy" , "/vagrant/consul_template"
      
      worker.vm.provision "shell", inline: "printf 'export HOST_IP_E=$(ip a | grep 'eth1' | grep inet | cut -d \" \" -f 6 | cut -d \"/\" -f 1)\n'  >> ~/.profile"
      worker.vm.provision "shell", inline: "printf 'export DNS_IP_E=$(ip a | grep 'docker0' | grep inet | cut -d \" \" -f 6 | cut -d \"/\" -f 1)\n'  >> ~/.profile"
      worker.vm.provision "shell", inline: "printf 'export SERVER_IP=#{SERVER_IP}'  >> ~/.profile"
      
      worker.vm.provision :docker
      worker.vm.provision :docker_compose, yml: "/vagrant/consul_template/consul_worker/docker-compose.yml", rebuild: true, run: "always"

    end
  end
end

$script = <<SCRIPT
echo "Updating apt-get"
apt-get update -qq
echo "installing https"
apt-get install -qq apt-transport-https ca-certificates 2>/dev/null
echo "inserting key"
apt-key adv -qq --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list
apt-get update -qq
echo "installing latest docker engine "
apt-get purge -qq --force-yes lxc-docker 2>/dev/null

apt-get install -qq --force-yes docker-engine 2>/dev/null

apt-get upgrade -qq --force-yes docker-engine 2>/dev/null

echo "installing curl"
apt-get install -qqy curl

curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` 2>/dev/null > /usr/local/bin/docker-compose
echo "installing docker-compose"
chmod +x /usr/local/bin/docker-compose

echo "cd /vagrant/consul_template" >> /home/vagrant/.bashrc

SCRIPT