version: "2"
services:
  consul_template1:
    build: ./consul-template
    container_name: consul_template
    ports:
      - 80:80
    links:
      - consul1:consul
    volumes:
      - "./consul-template/config/haproxy.json:/tmp/haproxy/haproxy.json"
      - "./consul-template/config/haproxy.ctmpl:/tmp/haproxy/haproxy.ctmpl"
    command: "consul-template -consul=consul:8500 -config=/tmp/haproxy/haproxy.json"

  consul1:
    image: "progrium/consul:latest"
    container_name: consul
    ports:
      - "${HOST_IP_E}:8300:8300"
      - "${HOST_IP_E}:8301:8301"
      - "${HOST_IP_E}:8301:8301/udp"
      - "${HOST_IP_E}:8302:8302"
      - "${HOST_IP_E}:8302:8302/udp"
      - "${HOST_IP_E}:8400:8400"
      - "${HOST_IP_E}:8500:8500"
      - "${DNS_IP_E}:53:53/udp"
    command: "-server -advertise ${HOST_IP_E} -bootstrap-expect 1"

  registrator:
    image: gliderlabs/registrator:master
    container_name: registrator
    hostname: registrator
    links:
      - consul1:consul
    volumes:
     - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consul:8500